add disk and memory usage probes to core service

diff --git a/k8s/deployment.yaml b/k8s/deployment.yaml
--- a/k8s/deployment.yaml
+++ b/k8s/deployment.yaml
@@ -26,7 +26,7 @@ spec:
               secretKeyRef:
                 name: pg-pass
                 key: password
-          readinessProbe:
+          livenessProbe:
             httpGet:
               path: /v1/heartbeat
               port: server
@@ -34,6 +34,22 @@ spec:
             periodSeconds: 10
             successThreshold: 1
             failureThreshold: 3
+          readinessProbe:
+            exec:
+              command:
+                - sh
+                - -c
+                - |
+                  disk_usage=$(df -h / | awk 'FNR == 2 {print $5}' | cut -d"%" -f1)
+                  memory_usage=$(free | awk 'FNR == 2 {print $3/$2 * 100}' | cut -d"." -f1)
+                  
+                  if [ "$disk_usage" -lt 80 ] && [ "$memory_usage" -lt 90 ]; then
+                    exit 0 # Success
+                  else
+                    exit 1 # Failure
+                  fi
+            initialDelaySeconds: 5
+            periodSeconds: 10
           ports:
             - containerPort: 3000
               name: server
